export * from './HomepageTemplate'
export * from './AboutusTemplate'
export * from './Navbar'
export * from './Footer'
export * from './EvchargingTemplate'
export * from './CloudsolutionTemplate'
export * from './IOTplatformTemplate'
